### ISSUE TITLE
Merging into Kaleidoscope?

### ISSUE THREAD

**Issue by algernon** [tremby/Kaleidoscope-LEDEffect-DigitalRain#12]
Hi!

I really like this effect, and it turns out, so do the people behind the [Dygma Raise](https://www.dygma.com/raise/), and they'd like to put it in their first firmware update. However, the plugin currently does not compile with Kaleidoscope master. I'd like to update it, and merge it into the Kaleidoscope repo.

Would you be ok with me doing that? No problem if not, then I'll submit a PR to update it to latest Kaleidoscope master, and will point a submodule here.

**Comment by tremby** [comment]
I've been meaning for a long time now to get my own firmware upgraded which
would necessitate this work. It keeps getting put on the back burner.

>
If you're keen go ahead, but this may be the kick I need, so there's a
chance I'll give it a shot tonight or tomorrow.

**Comment by tremby** [comment]
Work started in #13.

**Comment by tremby** [comment]
And done. I welcome any suggestions for optimizations or other changes before opening a pull request to Kaleidoscope.

**Comment by algernon** [comment]
So, a couple of things I'd change with regards to the plugin, with a Kaleidoscope merge in mind:

- It's probably worth transitioning to `TransientLEDMode`, because that can save significant amounts of RAM. I'm not very familiar with how to do that, but you can look at keyboardio/Kaleidoscope#617 for a few examples how other LED modes were transitioned. The PR has a fair amount of explanation too.
- In the past, we used member variables to control various properties of plugins, such as delays, colors, etc. More recently, we're slowly moving towards using accessors instead. The reason for that is that accessors are more future proof: if we want to deprecate a setting, we can do that with an accessor, but not with a directly-used member variable. If we want to change how a setting works, that's also easier with accessors. They just hide implementation details behind an user-visible API.
- I'd follow the Kaleidoscope naming scheme: private variables are lower- and snake-case, with a little tail at the end: `decay_ms_` for example. Public accessors are camelCase: `setDecayMs()`/`getDecayMs()`.
- It would be nice if the color channel could be named. Something like `LEDDigitalRainEffect.setColorChannel(LEDDigitalRainEffect::RED)` would be neat. To be super awesome, `setColorChannel()` would take an enum class, and `::RED` would be a `static constexpr ColorChannel RED = ColorChannel::RED` or something along those lines.
- `COLS` and `ROWS` are only used in `update()`, so you can make them local there, probably even constexpr, to save a few bytes of RAM. Or just use the longer stuff, though that does make things more verbose.
- Run `make astyle` :)

**Comment by tremby** [comment]
I've started this work.

If using a transient LED mode, should the configuration (`decay_ms_` etc) be in the child class or the parent class? Would the setters/accessors (`setDecayMs` etc) be in the child class or parent class? I can't find examples of setters/accessors for configuration purposes in any of the other plugins.

If the configuration is in the parent class, that'd still be taking up memory even when the LED mode isn't active, right? But maybe that's unavoidable, otherwise configuring (running the setters) during sketch setup wouldn't stick?

**Comment by algernon** [comment]
Settable (ie, non-private) members would be in the parent, and would take up memory indeed, and is unavoidable. But private members, like the timer helpers, and the map, those would be in the transient subclass, and _that_ would be the big RAM save in this case. `LEDDigitalRainEffect::map` is easily the biggest thing in there with its 64 bytes (on the Model01). The public settings are ~8 bytes, in comparison.

Setters would be in the parent. See the `LEDEffect-Rainbow` plugin for an example with setters and getters.

**Comment by tremby** [comment]
Ah, I didn't see these since they don't follow the `setX`/`getY` naming convention you mentioned. So should they be `setX`/`getX` or should they just be `x()` with optional parameter, like this rainbow one?

**Comment by tremby** [comment]
Assuming you meant what you originally said. I've made some changes. I'll open a self-PR for them and maybe you can review there.

**Comment by tremby** [comment]
Please see #14!

**Comment by hoijui** [comment]
ping @algernon

**Comment by tremby** [comment]
See https://github.com/keyboardio/Kaleidoscope/pull/1254
