### ISSUE TITLE
Request: Add link to getting started documentation

### ISSUE THREAD

**Issue by BrandonBoone** [tremby/Kaleidoscope-LEDEffect-DigitalRain#15]
A lot of these kaleidoscope plugins look awesome (yours especially), but almost all of them follow the same format of showing how to include the plugin without any links to a canonical "getting started with third party plugins" document.

Searching google, I'm not sure if there is a canonical guide out there or not, but I did find https://community.keyboard.io/t/seeking-feedback-on-guide-to-adding-a-3rd-party-plugin/3129 which seems useful (though I haven't worked through it yet).

Are you aware of a similar document being maintained somewhere, and if so, could you add a link to it on your README.md? Understood if it doesn't exist, but thought I would ask. Thanks!

**Comment by tremby** [comment]
I'm not aware of any such guide. The one you linked looks great, though. I'll add it to the readme. Thanks.
