### ISSUE TITLE
Update README for latest usage

### ISSUE THREAD

**Issue by h6y3** [tremby/Kaleidoscope-LEDEffect-DigitalRain#5]
The latest Kaleidoscope no longer uses a .use syntax and favors the use of KALEIDOSCOPE_INIT_PLUGINS.

Consider updating the README to reflect this.

**Comment by tremby** [comment]
Thanks for pointing this out. I'll likely do this next time I update my firmware. Or I'd accept a pull request with such a change in the mean time.
