### ISSUE TITLE
Animation very slow

### ISSUE THREAD

**Issue by jjochen** [tremby/Kaleidoscope-LEDEffect-DigitalRain#7]
Since my latest update of Kaleidoscope the digital rain effect is super slow. 
I tried to play around with `LEDDigitalRainEffect::DROP_TICKS` but that wasn't enough.

**Comment by tremby** [comment]
Fixed (finally) in v0.4.0. There's a configuration change. Won't affect you if you didn't customize anything, but if you did, check the readme (and header file if you like).
